# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Run the default task
    cmds:
      - task all
    silent: true

  push_master:
    desc: Push changes to the master branch
    cmds:
      - git push origin master
    silent: true

  commit:
    desc: Commit changes with a message
    cmds:
      - git add {{.files}}
      - git commit -m "{{.msg}}"
    silent: true

  pull:
    desc: Pull changes from the remote repository
    cmds:
      - git pull origin master
    silent: true

  checkout:
    desc: Checkout to a specific branch
    cmds:
      - git checkout {{.branch}}
    silent: true

  push:
    desc: Push changes to the current branch
    cmds:
      - git push origin HEAD
    silent: true

  tag:
    desc: Create a new tag
    cmds:
      - git tag {{.tag}}
      - git push origin {{.tag}}
    silent: true

  release:
    desc: Create a new release
    cmds:
      - git tag -a {{.tag}} -m "{{.msg}}"
      - git push origin {{.tag}}
    silent: true

  commit_push:
    desc: Commit and push changes
    cmds:
      - task commit msg="{{.msg}}" files="{{.files}}"
      - task push
    silent: true

  up-deps:
    desc: Update dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
    silent: true

  test:
    desc: Run tests
    cmds:
      - go test -v -cover -timeout 30s ./...
    env:
      GOFLAGS: -mod=readonly
    silent: true

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run --timeout 5m
    silent: true

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
    silent: true

  deps:
    desc: Install dependencies
    cmds:
      - go mod tidy
      - go mod download
    silent: true

  clean:
    desc: Clean up build artifacts
    cmds:
      - go clean -modcache
      - go clean -cache
      - go clean -testcache
    silent: true

  all:
    desc: Run all tasks
    cmds:
      - task clean
      - task deps
      - task up-deps
      - task fmt
      - task lint
      - task test
    silent: true
